version: '3.9'

services:
    db:
        image: postgres:14-bullseye
        ports: 
            - "5432:5432"
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: pings
        volumes:
            - ./pgdata:/var/lib/postgresql/data


